CREATE TABLE IF NOT EXISTS public."Shopping_Cart"
(
    "Shopping_Cart_Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "User_Id" character varying COLLATE pg_catalog."default" NOT NULL,
    "Cart_Created_Date" timestamp with time zone NOT NULL,
    "Created_Date" timestamp with time zone NOT NULL,
    "Created_By" character varying COLLATE pg_catalog."default" NOT NULL,
    "Modified_Date" timestamp with time zone,
    "Modified_By" character varying COLLATE pg_catalog."default",
    "Record_Version" numeric NOT NULL DEFAULT 1,
    CONSTRAINT "Shopping_Cart_pkey" PRIMARY KEY ("Shopping_Cart_Id"),
    CONSTRAINT "Cart_Items_fk_User_Id" FOREIGN KEY ("User_Id")
        REFERENCES public."AspNetUsers" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;